# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kisiler.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form1(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1061, 562)
        #Form.setFixedSize(1470,769)
        Form.setFixedSize(1061,562)
        self.anaFrame = QtWidgets.QFrame(Form)
        self.anaFrame.setGeometry(QtCore.QRect(0, 0, 1061, 561))
        self.anaFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.anaFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.anaFrame.setObjectName("anaFrame")
        self.listeSolFrame = QtWidgets.QFrame(self.anaFrame)
        self.listeSolFrame.setGeometry(QtCore.QRect(0, 40, 610, 521))
        self.listeSolFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.listeSolFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.listeSolFrame.setObjectName("listeSolFrame")
        self.tableWidget = QtWidgets.QTableWidget(self.listeSolFrame)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 610, 521))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.bilgiSagFrame = QtWidgets.QFrame(self.anaFrame)
        self.bilgiSagFrame.setGeometry(QtCore.QRect(610, 40, 450, 521))
        self.bilgiSagFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bilgiSagFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bilgiSagFrame.setObjectName("bilgiSagFrame")
        self.btnGuncelle = QtWidgets.QPushButton(self.bilgiSagFrame)
        self.btnGuncelle.setGeometry(QtCore.QRect(140, 440, 282, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnGuncelle.setFont(font)
        self.btnGuncelle.setObjectName("btnGuncelle")
        self.formLayoutWidget = QtWidgets.QWidget(self.bilgiSagFrame)
        self.formLayoutWidget.setGeometry(QtCore.QRect(60, 220, 361, 221))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.adLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.adLabel.setFont(font)
        self.adLabel.setObjectName("adLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.adLabel)
        self.adLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.adLineEdit.setFont(font)
        self.adLineEdit.setObjectName("adLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.adLineEdit)
        self.soyadLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.soyadLabel.setFont(font)
        self.soyadLabel.setObjectName("soyadLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.soyadLabel)
        self.soyadLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.soyadLineEdit.setFont(font)
        self.soyadLineEdit.setObjectName("soyadLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.soyadLineEdit)
        self.idLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.idLabel.setFont(font)
        self.idLabel.setObjectName("idLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.idLabel)
        self.idLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.idLineEdit.setFont(font)
        self.idLineEdit.setObjectName("idLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.idLineEdit)
        self.kimlikLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.kimlikLabel.setFont(font)
        self.kimlikLabel.setObjectName("kimlikLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.kimlikLabel)
        self.kimlikLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.kimlikLineEdit.setFont(font)
        self.kimlikLineEdit.setObjectName("kimlikLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.kimlikLineEdit)
        self.kurumLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.kurumLabel.setFont(font)
        self.kurumLabel.setObjectName("kurumLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.kurumLabel)
        self.kurumComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.kurumComboBox.setFont(font)
        self.kurumComboBox.setObjectName("kurumComboBox")
        self.kurumComboBox.addItem("")
        self.kurumComboBox.addItem("")
        self.kurumComboBox.addItem("")
        self.kurumComboBox.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.kurumComboBox)
        self.durumLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.durumLabel.setFont(font)
        self.durumLabel.setObjectName("durumLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.durumLabel)
        self.durumComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.durumComboBox.setFont(font)
        self.durumComboBox.setObjectName("durumComboBox")
        self.durumComboBox.addItem("")
        self.durumComboBox.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.durumComboBox)
        self.btnAktar = QtWidgets.QPushButton(self.bilgiSagFrame)
        self.btnAktar.setGeometry(QtCore.QRect(10, 10, 50, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnAktar.setFont(font)
        self.btnAktar.setObjectName("btnAktar")
        self.label = QtWidgets.QLabel(self.bilgiSagFrame)
        self.label.setGeometry(QtCore.QRect(60, 10, 361, 201))
        self.label.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lbl_kisiler = QtWidgets.QLabel(self.anaFrame)
        self.lbl_kisiler.setGeometry(QtCore.QRect(250, 10, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lbl_kisiler.setFont(font)
        self.lbl_kisiler.setStyleSheet("font: 75 14pt \"Arial\";")
        self.lbl_kisiler.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_kisiler.setObjectName("lbl_kisiler")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Cam view"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Ad"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Soyad"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "id"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Durum"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Kurum"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "TC Kimlik"))
        self.btnGuncelle.setText(_translate("Form", "Güncelle"))
        self.adLabel.setText(_translate("Form", "Ad"))
        self.soyadLabel.setText(_translate("Form", "Soyad"))
        self.idLabel.setText(_translate("Form", "ID"))
        self.kimlikLabel.setText(_translate("Form", "Kimlik"))
        self.kurumLabel.setText(_translate("Form", "Kurum"))
        self.kurumComboBox.setItemText(0, _translate("Form", "ATV"))
        self.kurumComboBox.setItemText(1, _translate("Form", "Ziyaretçi"))
        self.kurumComboBox.setItemText(2, _translate("Form", "Dış Personel"))
        self.kurumComboBox.setItemText(3, _translate("Form", "Taşeron"))
        self.durumLabel.setText(_translate("Form", "Durum"))
        self.durumComboBox.setItemText(0, _translate("Form", "İzinli"))
        self.durumComboBox.setItemText(1, _translate("Form", "İzinsiz"))
        self.btnAktar.setText(_translate("Form", ">>>"))
        self.label.setText(_translate("Form", "Resim "))
        self.lbl_kisiler.setText(_translate("Form", "Kişiler"))
        self.idLineEdit.setDisabled(True)
        self.kimlikLineEdit.setDisabled(True)
