# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kayit_yeni.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_KayitMainWindow(object):
    def setupUi(self, KayitMainWindow):
        KayitMainWindow.setObjectName("KayitMainWindow")
        KayitMainWindow.resize(760, 550)
        self.frame = QtWidgets.QFrame(KayitMainWindow)
        self.frame.setGeometry(QtCore.QRect(0, 0, 760, 550))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(45, 310, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btnTamam = QtWidgets.QPushButton(self.frame)
        self.btnTamam.setGeometry(QtCore.QRect(200, 510, 90, 30))
        self.btnTamam.setAutoRepeat(False)
        self.btnTamam.setObjectName("btnTamam")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 760, 300))
        self.label.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(45, 430, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btnFotoCek = QtWidgets.QPushButton(self.frame)
        self.btnFotoCek.setGeometry(QtCore.QRect(530, 350, 161, 30))
        self.btnFotoCek.setObjectName("btnFotoCek")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(380, 310, 111, 30))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(45, 350, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.btnKayitAl = QtWidgets.QPushButton(self.frame)
        self.btnKayitAl.setGeometry(QtCore.QRect(530, 390, 161, 30))
        self.btnKayitAl.setObjectName("btnKayitAl")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(530, 310, 161, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.txtAd = QtWidgets.QLineEdit(self.frame)
        self.txtAd.setGeometry(QtCore.QRect(150, 310, 200, 30))
        self.txtAd.setObjectName("txtAd")
        self.txtSoyad = QtWidgets.QLineEdit(self.frame)
        self.txtSoyad.setGeometry(QtCore.QRect(150, 350, 200, 30))
        self.txtSoyad.setObjectName("txtSoyad")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(45, 470, 71, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.kontrol = QtWidgets.QLabel(self.frame)
        self.kontrol.setGeometry(QtCore.QRect(720, 310, 41, 17))
        self.kontrol.setObjectName("kontrol")
        self.btnFotoCek2 = QtWidgets.QPushButton(self.frame)
        self.btnFotoCek2.setGeometry(QtCore.QRect(530, 430, 161, 30))
        self.btnFotoCek2.setObjectName("btnFotoCek2")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(370, 500, 230, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lblSayac = QtWidgets.QLabel(self.frame)
        self.lblSayac.setGeometry(QtCore.QRect(610, 500, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lblSayac.setFont(font)
        self.lblSayac.setObjectName("lblSayac")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(45, 390, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.txtKimlik = QtWidgets.QLineEdit(self.frame)
        self.txtKimlik.setGeometry(QtCore.QRect(150, 390, 200, 30))
        self.txtKimlik.setObjectName("txtKimlik")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame)
        self.comboBox_2.setGeometry(QtCore.QRect(150, 430, 200, 30))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.frame)
        self.comboBox_3.setGeometry(QtCore.QRect(150, 470, 200, 30))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")

        self.retranslateUi(KayitMainWindow)
        QtCore.QMetaObject.connectSlotsByName(KayitMainWindow)
        KayitMainWindow.setTabOrder(self.txtAd, self.txtSoyad)
        KayitMainWindow.setTabOrder(self.txtSoyad, self.btnTamam)
        KayitMainWindow.setTabOrder(self.btnTamam, self.lineEdit)
        KayitMainWindow.setTabOrder(self.lineEdit, self.btnFotoCek)
        KayitMainWindow.setTabOrder(self.btnFotoCek, self.btnKayitAl)
        KayitMainWindow.setTabOrder(self.btnKayitAl, self.comboBox)

    def retranslateUi(self, KayitMainWindow):
        _translate = QtCore.QCoreApplication.translate
        KayitMainWindow.setWindowTitle(_translate("KayitMainWindow", "Form"))
        self.label_2.setText(_translate("KayitMainWindow", "Adı :"))
        self.btnTamam.setText(_translate("KayitMainWindow", "Tamam"))
        self.label.setText(_translate("KayitMainWindow", "Kamera"))
        self.label_4.setText(_translate("KayitMainWindow", "Kurum :"))
        self.btnFotoCek.setText(_translate("KayitMainWindow", "Kamerayı Aç"))
        self.comboBox.setItemText(0, _translate("KayitMainWindow", "Cam1"))
        self.comboBox.setItemText(1, _translate("KayitMainWindow", "Cam2"))
        self.comboBox.setItemText(2, _translate("KayitMainWindow", "Cam3"))
        self.comboBox.setItemText(3, _translate("KayitMainWindow", "Cam4"))
        self.label_3.setText(_translate("KayitMainWindow", "Soyadı :"))
        self.btnKayitAl.setText(_translate("KayitMainWindow", "Video ile Kayıt"))
        self.lineEdit.setPlaceholderText(_translate("KayitMainWindow", "Fotoğraf Sayısı Giriniz"))
        self.txtAd.setPlaceholderText(_translate("KayitMainWindow", "Ad"))
        self.txtSoyad.setPlaceholderText(_translate("KayitMainWindow", "Soyad"))
        self.label_6.setText(_translate("KayitMainWindow", "Durum :"))
        self.kontrol.setText(_translate("KayitMainWindow", "False"))
        self.btnFotoCek2.setText(_translate("KayitMainWindow", "Tuş ile Kayıt"))
        self.label_7.setText(_translate("KayitMainWindow", "Çekilen Fotoğraf Sayısı :"))
        self.lblSayac.setText(_translate("KayitMainWindow", "0"))
        self.label_5.setText(_translate("KayitMainWindow", "Kimlik :"))
        self.txtKimlik.setPlaceholderText(_translate("KayitMainWindow", "TC Kimlik"))
        self.comboBox_2.setItemText(0, _translate("KayitMainWindow", "ATV"))
        self.comboBox_2.setItemText(1, _translate("KayitMainWindow", "Ziyaretçi"))
        self.comboBox_2.setItemText(2, _translate("KayitMainWindow", "Dış Personel"))
        self.comboBox_2.setItemText(3, _translate("KayitMainWindow", "Taşeron"))
        self.comboBox_3.setItemText(0, _translate("KayitMainWindow", "İzinli"))
        self.comboBox_3.setItemText(1, _translate("KayitMainWindow", "İzinsiz"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    KayitMainWindow = QtWidgets.QWidget()
    ui = Ui_KayitMainWindow()
    ui.setupUi(KayitMainWindow)
    KayitMainWindow.show()
    sys.exit(app.exec_())

