# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1470, 769)
        Form.setFixedSize(1470,769)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1471, 768))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.menuKismi = QtWidgets.QFrame(self.frame)
        self.menuKismi.setEnabled(True)
        self.menuKismi.setGeometry(QtCore.QRect(0, 0, 1471, 140))
        self.menuKismi.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.menuKismi.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menuKismi.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menuKismi.setObjectName("menuKismi")
        self.labelid = QtWidgets.QLabel(self.menuKismi)
        self.labelid.setGeometry(QtCore.QRect(140, 80, 67, 17))
        self.labelid.setStyleSheet("")
        self.labelid.setObjectName("labelid")
        self.labelAdSoyad = QtWidgets.QLabel(self.menuKismi)
        self.labelAdSoyad.setGeometry(QtCore.QRect(140, 20, 71, 17))
        self.labelAdSoyad.setStyleSheet("")
        self.labelAdSoyad.setObjectName("labelAdSoyad")
        self.labelizin = QtWidgets.QLabel(self.menuKismi)
        self.labelizin.setGeometry(QtCore.QRect(140, 60, 91, 17))
        self.labelizin.setStyleSheet("")
        self.labelizin.setObjectName("labelizin")
        self.labelGirisCikis = QtWidgets.QLabel(self.menuKismi)
        self.labelGirisCikis.setGeometry(QtCore.QRect(140, 40, 91, 17))
        self.labelGirisCikis.setStyleSheet("")
        self.labelGirisCikis.setObjectName("labelGirisCikis")
        self.lbl_AdSoyad = QtWidgets.QLabel(self.menuKismi)
        self.lbl_AdSoyad.setGeometry(QtCore.QRect(250, 20, 131, 17))
        self.lbl_AdSoyad.setStyleSheet("")
        self.lbl_AdSoyad.setObjectName("lbl_AdSoyad")
        self.lbl_izinli = QtWidgets.QLabel(self.menuKismi)
        self.lbl_izinli.setGeometry(QtCore.QRect(250, 60, 40, 17))
        self.lbl_izinli.setStyleSheet("color: rgb(115, 210, 22);")
        self.lbl_izinli.setObjectName("lbl_izinli")
        self.lblGiris = QtWidgets.QLabel(self.menuKismi)
        self.lblGiris.setGeometry(QtCore.QRect(250, 40, 50, 17))
        self.lblGiris.setStyleSheet("")
        self.lblGiris.setObjectName("lblGiris")
        self.lbl_ID = QtWidgets.QLabel(self.menuKismi)
        self.lbl_ID.setGeometry(QtCore.QRect(250, 80, 90, 17))
        self.lbl_ID.setStyleSheet("")
        self.lbl_ID.setObjectName("lbl_ID")
        self.lbl_izinsiz = QtWidgets.QLabel(self.menuKismi)
        self.lbl_izinsiz.setGeometry(QtCore.QRect(250, 60, 40, 17))
        self.lbl_izinsiz.setStyleSheet("color: rgb(204, 0, 0);")
        self.lbl_izinsiz.setObjectName("lbl_izinsiz")
        self.lblCikis = QtWidgets.QLabel(self.menuKismi)
        self.lblCikis.setGeometry(QtCore.QRect(250, 40, 50, 17))
        self.lblCikis.setStyleSheet("")
        self.lblCikis.setObjectName("lblCikis")
        self.btnKisiler = QtWidgets.QPushButton(self.menuKismi)
        self.btnKisiler.setGeometry(QtCore.QRect(1175, 20, 80, 80))
        self.btnKisiler.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnKisiler.setAutoFillBackground(False)
        self.btnKisiler.setStyleSheet("")
        self.btnKisiler.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resimler/images.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnKisiler.setIcon(icon)
        self.btnKisiler.setIconSize(QtCore.QSize(80, 80))
        self.btnKisiler.setObjectName("btnKisiler")
        self.btnKisiEkle = QtWidgets.QPushButton(self.menuKismi)
        self.btnKisiEkle.setGeometry(QtCore.QRect(1375, 20, 80, 80))
        self.btnKisiEkle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnKisiEkle.setAutoFillBackground(False)
        self.btnKisiEkle.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resimler/add-user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnKisiEkle.setIcon(icon1)
        self.btnKisiEkle.setIconSize(QtCore.QSize(80, 80))
        self.btnKisiEkle.setObjectName("btnKisiEkle")
        self.label_kisiler = QtWidgets.QLabel(self.menuKismi)
        self.label_kisiler.setGeometry(QtCore.QRect(1180, 105, 70, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_kisiler.setFont(font)
        self.label_kisiler.setAlignment(QtCore.Qt.AlignCenter)
        self.label_kisiler.setObjectName("label_kisiler")
        self.label_kayit = QtWidgets.QLabel(self.menuKismi)
        self.label_kayit.setGeometry(QtCore.QRect(1280, 105, 70, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_kayit.setFont(font)
        self.label_kayit.setAlignment(QtCore.Qt.AlignCenter)
        self.label_kayit.setObjectName("label_kayit")
        self.label_kisiEkle = QtWidgets.QLabel(self.menuKismi)
        self.label_kisiEkle.setGeometry(QtCore.QRect(1380, 105, 70, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_kisiEkle.setFont(font)
        self.label_kisiEkle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_kisiEkle.setObjectName("label_kisiEkle")
        self.btnKayit = QtWidgets.QPushButton(self.menuKismi)
        self.btnKayit.setGeometry(QtCore.QRect(1275, 20, 80, 80))
        self.btnKayit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnKayit.setAutoFillBackground(False)
        self.btnKayit.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resimler/kayit2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnKayit.setIcon(icon2)
        self.btnKayit.setIconSize(QtCore.QSize(80, 80))
        self.btnKayit.setObjectName("btnKayit")
        self.lblProfilFoto = QtWidgets.QLabel(self.menuKismi)
        self.lblProfilFoto.setGeometry(QtCore.QRect(10, 20, 100, 100))
        self.lblProfilFoto.setAutoFillBackground(False)
        self.lblProfilFoto.setStyleSheet("")
        self.lblProfilFoto.setText("")
        self.lblProfilFoto.setPixmap(QtGui.QPixmap("resimler/personReal.png"))
        self.lblProfilFoto.setScaledContents(True)
        self.lblProfilFoto.setObjectName("lblProfilFoto")
        self.control_bt_2 = QtWidgets.QPushButton(self.menuKismi)
        self.control_bt_2.setGeometry(QtCore.QRect(1010, 20, 141, 80))
        self.control_bt_2.setStyleSheet("")
        self.control_bt_2.setObjectName("control_bt_2")
        self.control_bt = QtWidgets.QPushButton(self.menuKismi)
        self.control_bt.setGeometry(QtCore.QRect(900, 20, 80, 80))
        self.control_bt.setObjectName("control_bt")
        self.pushButton = QtWidgets.QPushButton(self.menuKismi)
        self.pushButton.setGeometry(QtCore.QRect(400, 30, 71, 61))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.menuKismi)
        self.pushButton_2.setGeometry(QtCore.QRect(480, 30, 71, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.labelid.raise_()
        self.labelAdSoyad.raise_()
        self.labelizin.raise_()
        self.labelGirisCikis.raise_()
        self.lbl_AdSoyad.raise_()
        self.lbl_ID.raise_()
        self.lbl_izinsiz.raise_()
        self.lblCikis.raise_()
        self.btnKisiler.raise_()
        self.btnKisiEkle.raise_()
        self.label_kisiler.raise_()
        self.label_kayit.raise_()
        self.label_kisiEkle.raise_()
        self.btnKayit.raise_()
        self.lblProfilFoto.raise_()
        self.control_bt_2.raise_()
        self.control_bt.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.lbl_izinli.raise_()
        self.lblGiris.raise_()
        self.altFrame = QtWidgets.QFrame(self.frame)
        self.altFrame.setGeometry(QtCore.QRect(0, 140, 1470, 628))
        self.altFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.altFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.altFrame.setObjectName("altFrame")
        self.frame_2 = QtWidgets.QFrame(self.altFrame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 800, 628))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.image_label = QtWidgets.QLabel(self.frame_2)
        self.image_label.setGeometry(QtCore.QRect(0, 0, 400, 314))
        self.image_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.image_label.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label.setObjectName("image_label")
        self.image_label_2 = QtWidgets.QLabel(self.frame_2)
        self.image_label_2.setGeometry(QtCore.QRect(400, 0, 400, 314))
        self.image_label_2.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.image_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label_2.setObjectName("image_label_2")
        self.image_label_3 = QtWidgets.QLabel(self.frame_2)
        self.image_label_3.setGeometry(QtCore.QRect(0, 314, 400, 314))
        self.image_label_3.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.image_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label_3.setObjectName("image_label_3")
        self.image_label_4 = QtWidgets.QLabel(self.frame_2)
        self.image_label_4.setGeometry(QtCore.QRect(400, 314, 400, 314))
        self.image_label_4.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.image_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label_4.setObjectName("image_label_4")
        self.kayitFrame = QtWidgets.QFrame(self.altFrame)
        self.kayitFrame.setGeometry(QtCore.QRect(800, 0, 671, 628))
        self.kayitFrame.setStyleSheet("")
        self.kayitFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.kayitFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.kayitFrame.setObjectName("kayitFrame")
        self.tableWidget = QtWidgets.QTableWidget(self.kayitFrame)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 671, 628))
        self.tableWidget.setStyleSheet("selection-background-color: rgb(233, 185, 110);")
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.lbl_AdSoyad.setBuddy(self.btnKisiler)
        self.lblProfilFoto.setBuddy(self.btnKisiler)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.control_bt, self.btnKisiler)
        Form.setTabOrder(self.btnKisiler, self.btnKayit)
        Form.setTabOrder(self.btnKayit, self.btnKisiEkle)
        Form.setTabOrder(self.btnKisiEkle, self.pushButton)
        Form.setTabOrder(self.pushButton, self.control_bt_2)
        Form.setTabOrder(self.control_bt_2, self.pushButton_2)
        Form.setTabOrder(self.pushButton_2, self.tableWidget)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Cam view"))
        self.labelid.setText(_translate("Form", "ID :"))
        self.labelAdSoyad.setText(_translate("Form", "Ad Soyad :"))
        self.labelizin.setText(_translate("Form", "İzin Durumu"))
        self.labelGirisCikis.setText(_translate("Form", "<html><head/><body><p>Giriş / Çıkış :</p></body></html>"))
        self.lbl_AdSoyad.setText(_translate("Form", "Ad Soyadi"))
        self.lbl_izinli.setText(_translate("Form", "İzinli"))
        self.lblGiris.setText(_translate("Form", "Giriş"))
        self.lbl_ID.setText(_translate("Form", "Id Numarasi"))
        self.lbl_izinsiz.setText(_translate("Form", "İzinsiz"))
        self.lblCikis.setText(_translate("Form", "Çıkış"))
        self.label_kisiler.setText(_translate("Form", "Kişiler"))
        self.label_kayit.setText(_translate("Form", "Kayıtlar"))
        self.label_kisiEkle.setText(_translate("Form", "Kişi Ekle"))
        self.control_bt_2.setText(_translate("Form", "Veritabanı Güncelle"))
        self.control_bt.setText(_translate("Form", "Start"))
        self.pushButton.setText(_translate("Form", "1"))
        self.pushButton_2.setText(_translate("Form", "2"))
        self.image_label.setText(_translate("Form", "TextLabel"))
        self.image_label_2.setText(_translate("Form", "TextLabel"))
        self.image_label_3.setText(_translate("Form", "TextLabel"))
        self.image_label_4.setText(_translate("Form", "TextLabel"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "İzin Durumu"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Giriş/Çıkış"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Ad"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Soyad"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Tarih"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Saat"))


